Make message about invalid problem directory more clear

diff --git a/src/reporter-vz b/src/reporter-vz
--- a/src/reporter-vz
+++ b/src/reporter-vz
@@ -42,7 +42,12 @@ if [ ! -d "$workdir" ]; then
 fi
 
 if [[ ! -f "$workdir/executable" || ! -f "$workdir/pkg_version" || ! -f "$workdir/pkg_release" || ! -f "$workdir/pid" || ! -f "$workdir/cmdline" ]]; then
-  >&2 echo "Error: $(readlink -f $workdir) is not a problem directory."
+  >&2 echo "Error: $(readlink -f $workdir) is not a valid problem directory."
+  >&2 echo "It doesn't contain one of the required files: "
+  [ -f "$workdir/executable" ]  || >&2 echo "  executable"
+  [ -f "$workdir/pkg_release" ] || >&2 echo "  pkg_release"
+  [ -f "$workdir/pid" ]         || >&2 echo "  pid"
+  [ -f "$workdir/cmdline" ]     || >&2 echo "  cmdline"
   >&2 echo "Usage: ${0} <dir>"
   exit -1
 fi
